---
title: "Two Axis Cart Pole"
format:
  html:
    code-fold: true
---

## Environment

A frame of the system can be expressed as: 
$\textbf{x} = \left[ x, y, \theta_x, \theta_y, \dot{x}, \dot y, \dot{\theta_x}, \dot{\theta_y} \right]$



| Variable | Description | minVal | maxVal
| ----- | ----- | --- | --- |
| $x$ | carts position along x-axis | -2 | 2 |
| $y$ | carts position along y-axis | -2 | 2 |
| $\theta_x$ | poles angle along the x axis about the cart in radians | $0$ | $2\pi$ |
| $\theta_y$ | poles angle along the y axis about the cart in radian | $0$ | $2\pi$|
| $\dot x$ | be the linear velocity of cart along x-axis | $-\infty$ | $\infty$ |
| $\dot y$ | be then linear velocity of cart along y-axis | $-\infty$ | $\infty$ |
| $\dot \theta_x$ | the angular velocity of the pole along the x axis about the cart | $-\infty$ | $\infty$ |
| $\dot \theta_y$ | the angular velocity of the pole along the y axis about the cart | $-\infty$ | $\infty$ |


### Kinematics

For the small-angle model used in the LQR linearization, the position and velocity of the mass at the end of the pendulum with a massless rod may be approximated as follows:

$$\textbf{x}_{p} = \begin{bmatrix} x_p \\ y_p \\ z_p \end{bmatrix} =
\begin{bmatrix}
x_c + \ell\sin(\theta_x) \\
y_c + \ell\sin(\theta_y) \\
\ell\cos(\theta_x)\cos(\theta_y)
\end{bmatrix}$$

$$\dot{\textbf{x}}_{p} = \begin{bmatrix} \dot x_p \\ \dot y_p \\ \dot z_p
\end{bmatrix}
= \begin{bmatrix}
\dot x_c + \ell \cos(\theta_x) \dot \theta_x \\
\dot y_c + \ell \cos(\theta_y) \dot \theta_y \\
-\ell \sin{(\theta_x)}\cos{(\theta_y)} \dot\theta_x - \ell \sin{(\theta_y)}\cos{(\theta_x)} \dot \theta_y
\end{bmatrix}$$

### Lagrangian

The first step in creating an LQR controller is the linearize the systems equation of motions about a fixed point. We can calculate these equations using the Lagrangian which state that,
$$L = T - V$$ 
where $T$ and $V$ represent the kinetic and potential energy of the system respectively, obtaining:

- #### Kinetic Energy
Applying the equation for Kinetic Energy ($KE = \frac{1}{2}mv^2$) yields:
$$T_p = \frac{1}{2} m_p(\dot x_p^2 + \dot y_p^2 + \dot z_p^2)$$
$$T_c = \frac{1}{2} m_c(\dot x_c^2 + \dot y_c^2)$$
$$T = T_p + T_c$$

- #### Potential Energy
The potential energy of the effect of gravity on the pendulum mass ($V = mgh)$ is the only source considered (energy of the cart is not considered).

$$V = m_p g \ell \cos(\theta_x) \cos(\theta_y) $$

- #### Full Equations
$$L =\frac{1}{2} \left(m_p (\dot x_p^2 + \dot y_p^2 + \dot z_p^2) + m_c (\dot x_c^2 + \dot y_c^2)  \right) - m_p g \ell \cos(\theta_x) \cos(\theta_y) $$

### Equations of Motion 
Using the methods of Lagrange, we can write the equation of motion using generalized coordinates. The dynamics equations ($Q_i$) for the generalized coordinates ($q_i$) is obtained from the equation:
$$\frac{d}{dt}\left(\frac{\partial L}{\partial \dot q_i}\right) - \frac{\partial L}{\partial q_i} = Q_i$$
In this system, the generalized coordinates chosen will be $q =\left[x_c , y_c,  \theta_x,  \theta_y \right]$.  Since there are variables in $L$ that are not in $q$, substituting them for their equivalent to contain only values from $q$ reveals:

$$L = \frac{1}{2}\left( m_p\left[ \left(\dot x_c + \ell\cos(\theta_x)\dot \theta_x\right)^2 + \left(\dot y_c +\ell\cos(\theta_y)\dot\theta_y \right)^2 + \left(-\ell \sin{(\theta_x)}\cos{(\theta_y)} \dot\theta_x - \ell \sin{(\theta_y)}\cos{(\theta_x)} \dot \theta_y\right)^2\right] + m_c(\dot x_c^2 +\dot y_c^2)\right) -m_p g\ell\cos(\theta_x)\cos(\theta_y)$$


The following is the grueling process of deriving all of the equations of motions and substitution to contain only generalized coordinates and constants.

- #### $x_c$

  - $\frac{\partial L}{\partial \dot x_c}$ 
  $$\boxed{\dot x_c(m_c + m_p) + m_p \ell \cos(\theta_x)\dot \theta_x}$$

    
  - $\frac{d}{dt} \left( \frac{\partial L}{\partial \dot x_c}\right)$
  $$\boxed{\ddot x_c( m_c + m_p)+ m_p \ell \left(\cos(\theta_x)\ddot \theta_x - \sin(\theta_x)\dot \theta_x^2 \right)}$$

  - $\frac{\partial L}{\partial x_c}$
  $$\boxed{0}$$

  - $F_x$
  $$\boxed{F_x = \ddot x_c(m_c+m_p) + m_p\ell\left(\cos(\theta_x)\ddot \theta_x-\sin(\theta_x)\dot \theta_x^2 \right)}$$



- ####  $\theta_x$
  - $\frac{\partial L}{\partial \dot \theta_x}$
  <!-- $$m_p\ell\cos(\theta_x)\dot x_c+\dot{\theta_x}\left[m_p\ell^2\cos^2(\theta_x)+m_p\ell^2\sin^2(\theta_x)\cos^2(\theta_y)+ I\right] + m_p\ell^2\sin(\theta_x)\sin(\theta_y)\cos(\theta_x)\cos(\theta_y)\dot \theta_y$$ -->



  <!-- Since the LQR controller will be for stabilizing the system when near its unstable equilibrium, we can make the equations simpler by applying small angle approximations such as:
    - $\cos^2(\theta) \approx 1$
    - $\sin^2(\theta) \approx 0$
    - $\sin(\theta_x)\sin(\theta_y)\cos(\theta_x)\cos(\theta_y) \approx 0$
    - $\cos(\theta)\sin(\theta) \approx 0$ -->

  <!-- producing:
  $$\boxed{m_p\ell\cos(\theta_x)\dot x_c + \dot \theta_x\left[m_p\ell^2 +I\right]}$$ -->

$$\boxed{m_p \ell \cos(\theta_x)\dot x_c + m_p\ell^2\dot\theta_x}$$


  - $\frac{d}{dt}\left(\frac{\partial L}{\partial \dot \theta_x}\right)$
  $$\boxed{m_p\ell\cos(\theta_x)\ddot x_c-m_p\ell\sin(\theta_x)\dot\theta_x\dot x_c+m_p\ell^2\ddot\theta_x}$$



  - $\frac{\partial L}{\partial \theta_x}$
  $${m_p\left[(\dot x + \ell\cos(\theta_x)\dot\theta_x)\cdot(-\sin(\theta_x)\dot\theta_x) + (-\ell\sin(\theta_x)\cos(\theta_y)\dot\theta_x-\ell\sin(\theta_y)\cos(\theta_x)\dot\theta_y)\cdot(\ell\sin(\theta_y)\sin(\theta_x)\dot\theta_y-\ell\cos(\theta_x)\cos(\theta_y)\dot\theta_x)\right]+m_pg\ell\sin(\theta_x)\cos(\theta_y)}$$

$$\boxed{m_pg\ell\sin(\theta_x)}$$


  - $F_{\theta_x}$

  After applying small angle approximations,
  $$\boxed{m_p\ell\ddot x_c+m_p\ell^2\ddot\theta_x-m_pg\ell\theta_x = 0}$$

The others can be derived by symmetry.

### Linearization

LQR requires that the dynamics of system be modeled as the linear equation $\dot{\textbf{x}} = A\textbf{x} + Bu$ around a stable fixed point (the pendulum-up position) as $\textbf{x}_{f} =[x_c, y_c, 0, 0]$ and $\dot{\textbf{x}}_f = [0, 0, 0, 0]$ using only control inputs $u = [F_x, F_y]$.


  - $\cos(\theta) \approx 1$
  - $\sin(\theta) \approx \theta$
  - $\theta^2 \approx 0$

For the massless rod and point-mass model, the point-mass rotational inertia is already included in the translational kinetic energy. Let $J = m_p\ell^2$. If the pole has non-negligible inertia, use $J = I_p + m_p\ell^2$ instead.

We can pose the problem as a coupled equation and solve for $\ddot x_c$ and $\ddot\theta_x$.

$$\begin{aligned} \ddot x_c (m_c + m_p) + m_p \ell \ddot \theta_x = F_{x}\\
m_p \ell \ddot x_c + J \ddot \theta_x - m_p g \ell \theta_x =  0 \end{aligned}$$

Which can be solved by:

$$\begin{bmatrix}(m_c + m_p) & m_p \ell \\ m_p\ell & J\end{bmatrix}
\begin{bmatrix} \ddot x_c \\ \ddot\theta_x\end{bmatrix} =
\begin{bmatrix} F_x \\ m_p g \ell \theta_x\end{bmatrix}$$

where

$$D = (m_c + m_p)J - (m_p\ell)^2$$

$$\begin{bmatrix}\ddot x_c \\ \ddot \theta_x\end{bmatrix} = \frac{1}{D}\begin{bmatrix}JF_x - m_p^2\ell^2g\theta_x \\ -m_p\ell F_x + (m_c+m_p)m_pg\ell\theta_x\end{bmatrix}$$

Revealing the coefficients to be:

$$\ddot x_c = F_x \underbrace{\frac{J}{D}}_p - \theta_x \underbrace{\frac{m_p^2\ell^2g}{D}}_q$$

$$\ddot \theta_x = -F_x \underbrace{\frac{m_p\ell}{D}}_r + \theta_x \underbrace{\frac{(m_c + m_p)(m_p\ell g)}{D}}_s$$

Since the system is symmetric, the coefficients for $\ddot y_c$ and $\ddot \theta_y$ are the same.

### LQR / Cost-2-Go
<!-- For notation, let $p = \frac{J}{D}$, $q = \frac{m_p^2\ell^2g}{D}$, $r = \frac{m_p\ell}{D}$ and $s = \frac{(m_c+m_p)(m_p\ell g)}{D}$ -->

LQR requires the system to be written as a linear equation

$$\begin{bmatrix} \dot x_c \\ \dot y_c \\ \dot \theta_x \\ \dot \theta_y \\ \ddot x_c \\ \ddot y_c \\ \ddot \theta_x \\ \ddot \theta_y \end{bmatrix}  = A \begin{bmatrix} x_c \\  y_c \\ \theta_x \\ \theta_y \\ \dot x_c \\ \dot y_c \\ \dot \theta_x \\ \dot \theta_y \end{bmatrix} + B \begin{bmatrix} F_x \\ F_y\end{bmatrix}$$



The non-trivial values of $A$ are:

$$A = \begin{bmatrix}
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0  \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0  \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0  \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1  \\
0 & 0 & -q & 0 & 0 & 0 & 0 & 0  \\
0 & 0 & 0 & -q & 0 & 0 & 0 & 0  \\
0 & 0 & s & 0 & 0 & 0 & 0 & 0  \\
0 & 0 & 0 & s & 0 & 0 & 0 & 0  \\
\end{bmatrix}$$

$$B = \begin{bmatrix}
0 & 0 \\
0 & 0 \\
0 & 0 \\
0 & 0 \\
p & 0 \\
0 & p \\
-r & 0 \\
0 & -r \\
\end{bmatrix}$$
